#默认使用配置
spring:
  profiles:
    active: dev
  application:
    name: customer

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.huawei.cse.democustomer.entity
  mapperLocations: classpath:mapper/*.xml
